export type AutopilotBusinessStage =
  | "idea"
  | "pre_launch"
  | "onboarding"
  | "early_revenue"
  | "growth";

export type AutopilotRiskTolerance = "low" | "medium" | "high";

export type AutopilotProfileInput = {
  businessStage: AutopilotBusinessStage;
  northStarMetric: string;
  weeklyGoal: string;
  constraints: string[];
  channels: string[];
  targetAudience: string;
  timeBudgetHoursPerWeek: number;
  riskTolerance: AutopilotRiskTolerance;
};

export type PlanningTaskCandidate = {
  title: string;
  description: string;
  priority: "high" | "medium" | "low" | "none";
  status: "inbox" | "assigned" | "in_progress" | "review" | "done" | "blocked";
  assigneeSessionKey: string;
  dueAt: number | null;
  whyNow: string;
  dedupeKey: string;
  confidence: number;
  kpiImpactScore: number;
  actionType: string;
};

function clean(value: string): string {
  return value.trim().replace(/\s+/g, " ");
}

export function normalizeTitle(input: string): string {
  return clean(input).toLowerCase();
}

export async function sha256Hex(value: string): Promise<string> {
  const hash = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return Array.from(new Uint8Array(hash))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export async function buildDedupeKey(args: {
  title: string;
  primaryKpi: string;
  targetSegment: string;
  actionType: string;
}): Promise<string> {
  const canonical = [
    normalizeTitle(args.title),
    clean(args.primaryKpi).toLowerCase(),
    clean(args.targetSegment).toLowerCase(),
    clean(args.actionType).toLowerCase(),
  ].join("|");
  return await sha256Hex(canonical);
}

function priorityScore(priority: PlanningTaskCandidate["priority"]): number {
  if (priority === "high") return 3;
  if (priority === "medium") return 2;
  if (priority === "low") return 1;
  return 0;
}

export function rankCandidates(candidates: PlanningTaskCandidate[]): PlanningTaskCandidate[] {
  return [...candidates].sort((a, b) => {
    const scoreA = priorityScore(a.priority) + a.confidence * 2 + a.kpiImpactScore;
    const scoreB = priorityScore(b.priority) + b.confidence * 2 + b.kpiImpactScore;
    return scoreB - scoreA;
  });
}

export function firstNonEmpty(values: Array<string | undefined | null>, fallback: string): string {
  for (const value of values) {
    const cleanValue = value?.trim();
    if (cleanValue) return cleanValue;
  }
  return fallback;
}

export function buildStrategyDocumentContent(args: {
  objective: string;
  kpiTarget: string;
  profile: AutopilotProfileInput;
  assumptions: string[];
  risks: string[];
  blockedBy: string[];
  selected: PlanningTaskCandidate[];
  skipped: Array<{ title: string; reason: string }>;
}): string {
  const lines: string[] = [];
  lines.push("# Weekly Autopilot Plan");
  lines.push("");
  lines.push("## Objective");
  lines.push(args.objective);
  lines.push("");
  lines.push("## KPI Target");
  lines.push(args.kpiTarget);
  lines.push("");
  lines.push("## Founder Brief Snapshot");
  lines.push(`- Stage: ${args.profile.businessStage}`);
  lines.push(`- Weekly goal: ${args.profile.weeklyGoal}`);
  lines.push(`- North star metric: ${args.profile.northStarMetric}`);
  lines.push(`- Target audience: ${args.profile.targetAudience}`);
  lines.push(`- Channels: ${args.profile.channels.join(", ") || "n/a"}`);
  lines.push(`- Constraints: ${args.profile.constraints.join(" | ") || "n/a"}`);
  lines.push(`- Time budget (hours/week): ${args.profile.timeBudgetHoursPerWeek}`);
  lines.push(`- Risk tolerance: ${args.profile.riskTolerance}`);
  lines.push("");
  lines.push("## Prioritized Tasks");
  args.selected.forEach((task, index) => {
    lines.push(`${index + 1}. ${task.title}`);
    lines.push(`   - Priority: ${task.priority}`);
    lines.push(`   - Confidence: ${task.confidence.toFixed(2)}`);
    lines.push(`   - Why now: ${task.whyNow}`);
  });
  lines.push("");
  lines.push("## Skipped Duplicates");
  if (args.skipped.length === 0) {
    lines.push("- None");
  } else {
    args.skipped.forEach((item) => {
      lines.push(`- ${item.title}: ${item.reason}`);
    });
  }
  lines.push("");
  lines.push("## Assumptions");
  args.assumptions.forEach((item) => lines.push(`- ${item}`));
  lines.push("");
  lines.push("## Risks");
  args.risks.forEach((item) => lines.push(`- ${item}`));
  lines.push("");
  lines.push("## Blockers");
  args.blockedBy.forEach((item) => lines.push(`- ${item}`));
  lines.push("");
  lines.push("---");
  lines.push("Generated by Autopilot v1 (Business Onboarding Growth)");
  return lines.join("\n");
}
