# fly.toml app configuration file generated for sutraha-openclaw-bridge on 2026-02-13T12:28:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sutraha-openclaw-bridge'
primary_region = 'bom'

[build]
  dockerfile = "dockerfile"

[env]
  NODE_ENV = "production"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
